version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: Sockpuppet-Sentinel-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - ai-security-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: Sockpuppet-Sentinel-frontend
    ports:
      - "5173:80"
    environment:
      NODE_ENV: development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - ai-security-net

networks:
  ai-security-net:
    driver: bridge
